exec_timeout_secs: 7200

functions:
  checkout:
    - command: git.get_project
      params:
        directory: src

  test_expansion_on_linux:
    - command: expansions.write
      params:
        file: tmp/expansions.yaml
        redacted: true
    - command: shell.exec
      params:
        working_dir: src
        shell: bash
        script: |
          pwd
          ls ../tmp

  test_expansion_on_windows:
    - command: expansions.write
      params:
        file: tmp\expansions.yaml
        redacted: true
    - command: shell.exec
      params:
        working_dir: src
        shell: powershell
        script: |
          pwd
          ls ..\tmp\

tasks:
  - name: test_expansion_on_linux
    commands:
      - func: checkout
      - func: test_expansion_on_linux
  - name: test_expansion_on_windows
    commands:
      - func: checkout
      - func: test_expansion_on_windows

buildvariants:
  - name: ubuntu
    display_name: "Ubuntu 18.04"
    run_on: ubuntu1804-test
    tasks:
      - name: test_expansion_on_linux
  - name: windows_ps
    display_name: "Windows VS 2019 PowerShell"
    run_on: windows-64-vs2019-test
    tasks:
      - name: test_expansion_on_windows
